#ifndef GUARD_CONSTANTS_EVENT_OBJECTS_H
#define GUARD_CONSTANTS_EVENT_OBJECTS_H

#define EVENT_OBJ_GFX_PROTAG_BOY1_NORMAL             0x00
#define EVENT_OBJ_GFX_PROTAG_BOY1_MACH_BIKE          0x01
#define EVENT_OBJ_GFX_PROTAG_BOY1_ACRO_BIKE          0x02
#define EVENT_OBJ_GFX_PROTAG_BOY1_SURFING            0x03
#define EVENT_OBJ_GFX_PROTAG_BOY1_FIELD_MOVE         0x04
#define EVENT_OBJ_GFX_PROTAG_BOY1_UNDERWATER         0x05
#define EVENT_OBJ_GFX_PROTAG_BOY1_FISHING            0x06
#define EVENT_OBJ_GFX_PROTAG_BOY1_WATERING           0x07
#define EVENT_OBJ_GFX_PROTAG_GIRL1_NORMAL            0x08
#define EVENT_OBJ_GFX_PROTAG_GIRL1_MACH_BIKE         0x09
#define EVENT_OBJ_GFX_PROTAG_GIRL1_ACRO_BIKE         0x0A
#define EVENT_OBJ_GFX_PROTAG_GIRL1_SURFING           0x0B
#define EVENT_OBJ_GFX_PROTAG_GIRL1_FIELD_MOVE        0x0C
#define EVENT_OBJ_GFX_PROTAG_GIRL1_UNDERWATER        0x0D
#define EVENT_OBJ_GFX_PROTAG_GIRL1_FISHING           0x0E
#define EVENT_OBJ_GFX_PROTAG_GIRL1_WATERING          0x0F

#define EVENT_OBJ_GFX_PROTAG_BOY2_NORMAL             0x10
#define EVENT_OBJ_GFX_PROTAG_BOY2_MACH_BIKE          0x11
#define EVENT_OBJ_GFX_PROTAG_BOY2_ACRO_BIKE          0x12
#define EVENT_OBJ_GFX_PROTAG_BOY2_SURFING            0x13
#define EVENT_OBJ_GFX_PROTAG_BOY2_FIELD_MOVE         0x14
#define EVENT_OBJ_GFX_PROTAG_BOY2_UNDERWATER         0x15
#define EVENT_OBJ_GFX_PROTAG_BOY2_FISHING            0x16
#define EVENT_OBJ_GFX_PROTAG_BOY2_WATERING           0x17
#define EVENT_OBJ_GFX_PROTAG_GIRL2_NORMAL            0x18
#define EVENT_OBJ_GFX_PROTAG_GIRL2_MACH_BIKE         0x19
#define EVENT_OBJ_GFX_PROTAG_GIRL2_ACRO_BIKE         0x1A
#define EVENT_OBJ_GFX_PROTAG_GIRL2_SURFING           0x1B
#define EVENT_OBJ_GFX_PROTAG_GIRL2_FIELD_MOVE        0x1C
#define EVENT_OBJ_GFX_PROTAG_GIRL2_UNDERWATER        0x1D
#define EVENT_OBJ_GFX_PROTAG_GIRL2_FISHING           0x1E
#define EVENT_OBJ_GFX_PROTAG_GIRL2_WATERING          0x1F

#define EVENT_OBJ_GFX_PROTAG_BOY3_NORMAL             0x20
#define EVENT_OBJ_GFX_PROTAG_BOY3_MACH_BIKE          0x21
#define EVENT_OBJ_GFX_PROTAG_BOY3_ACRO_BIKE          0x22
#define EVENT_OBJ_GFX_PROTAG_BOY3_SURFING            0x23
#define EVENT_OBJ_GFX_PROTAG_BOY3_FIELD_MOVE         0x24
#define EVENT_OBJ_GFX_PROTAG_BOY3_UNDERWATER         0x25
#define EVENT_OBJ_GFX_PROTAG_BOY3_FISHING            0x26
#define EVENT_OBJ_GFX_PROTAG_BOY3_WATERING           0x27
#define EVENT_OBJ_GFX_PROTAG_GIRL3_NORMAL            0x28
#define EVENT_OBJ_GFX_PROTAG_GIRL3_MACH_BIKE         0x29
#define EVENT_OBJ_GFX_PROTAG_GIRL3_ACRO_BIKE         0x2A
#define EVENT_OBJ_GFX_PROTAG_GIRL3_SURFING           0x2B
#define EVENT_OBJ_GFX_PROTAG_GIRL3_FIELD_MOVE        0x2C
#define EVENT_OBJ_GFX_PROTAG_GIRL3_UNDERWATER        0x2D
#define EVENT_OBJ_GFX_PROTAG_GIRL3_FISHING           0x2E
#define EVENT_OBJ_GFX_PROTAG_GIRL3_WATERING          0x2F

#define EVENT_OBJ_GFX_PROTAG_BOY4_NORMAL             0x30
#define EVENT_OBJ_GFX_PROTAG_BOY4_MACH_BIKE          0x31
#define EVENT_OBJ_GFX_PROTAG_BOY4_ACRO_BIKE          0x32
#define EVENT_OBJ_GFX_PROTAG_BOY4_SURFING            0x33
#define EVENT_OBJ_GFX_PROTAG_BOY4_FIELD_MOVE         0x34
#define EVENT_OBJ_GFX_PROTAG_BOY4_UNDERWATER         0x35
#define EVENT_OBJ_GFX_PROTAG_BOY4_FISHING            0x36
#define EVENT_OBJ_GFX_PROTAG_BOY4_WATERING           0x37
#define EVENT_OBJ_GFX_PROTAG_GIRL4_NORMAL            0x38
#define EVENT_OBJ_GFX_PROTAG_GIRL4_MACH_BIKE         0x39
#define EVENT_OBJ_GFX_PROTAG_GIRL4_ACRO_BIKE         0x3A
#define EVENT_OBJ_GFX_PROTAG_GIRL4_SURFING           0x3B
#define EVENT_OBJ_GFX_PROTAG_GIRL4_FIELD_MOVE        0x3C
#define EVENT_OBJ_GFX_PROTAG_GIRL4_UNDERWATER        0x3D
#define EVENT_OBJ_GFX_PROTAG_GIRL4_FISHING           0x3E
#define EVENT_OBJ_GFX_PROTAG_GIRL4_WATERING          0x3F

#define EVENT_OBJ_GFX_PROTAG_BOY5_NORMAL             0x40
#define EVENT_OBJ_GFX_PROTAG_BOY5_MACH_BIKE          0x41
#define EVENT_OBJ_GFX_PROTAG_BOY5_ACRO_BIKE          0x42
#define EVENT_OBJ_GFX_PROTAG_BOY5_SURFING            0x43
#define EVENT_OBJ_GFX_PROTAG_BOY5_FIELD_MOVE         0x44
#define EVENT_OBJ_GFX_PROTAG_BOY5_UNDERWATER         0x45
#define EVENT_OBJ_GFX_PROTAG_BOY5_FISHING            0x46
#define EVENT_OBJ_GFX_PROTAG_BOY5_WATERING           0x47
#define EVENT_OBJ_GFX_PROTAG_GIRL5_NORMAL            0x48
#define EVENT_OBJ_GFX_PROTAG_GIRL5_MACH_BIKE         0x49
#define EVENT_OBJ_GFX_PROTAG_GIRL5_ACRO_BIKE         0x4A
#define EVENT_OBJ_GFX_PROTAG_GIRL5_SURFING           0x4B
#define EVENT_OBJ_GFX_PROTAG_GIRL5_FIELD_MOVE        0x4C
#define EVENT_OBJ_GFX_PROTAG_GIRL5_UNDERWATER        0x4D
#define EVENT_OBJ_GFX_PROTAG_GIRL5_FISHING           0x4E
#define EVENT_OBJ_GFX_PROTAG_GIRL5_WATERING          0x4F

#define EVENT_OBJ_GFX_RIVAL_BRENDAN_NORMAL           0x50
#define EVENT_OBJ_GFX_RIVAL_BRENDAN_MACH_BIKE        0x51
#define EVENT_OBJ_GFX_RIVAL_BRENDAN_ACRO_BIKE        0x52
#define EVENT_OBJ_GFX_RIVAL_BRENDAN_SURFING          0x53
#define EVENT_OBJ_GFX_RIVAL_BRENDAN_FIELD_MOVE       0x54
#define EVENT_OBJ_GFX_RIVAL_BRENDAN_UNDERWATER       0x55
#define EVENT_OBJ_GFX_RIVAL_BRENDAN_FISHING          0x56
#define EVENT_OBJ_GFX_RIVAL_BRENDAN_WATERING         0x57
#define EVENT_OBJ_GFX_RIVAL_MAY_NORMAL               0x58
#define EVENT_OBJ_GFX_RIVAL_MAY_MACH_BIKE            0x59
#define EVENT_OBJ_GFX_RIVAL_MAY_ACRO_BIKE            0x5A
#define EVENT_OBJ_GFX_RIVAL_MAY_SURFING              0x5B
#define EVENT_OBJ_GFX_RIVAL_MAY_FIELD_MOVE           0x5C
#define EVENT_OBJ_GFX_RIVAL_MAY_UNDERWATER           0x5D
#define EVENT_OBJ_GFX_RIVAL_MAY_FISHING              0x5E
#define EVENT_OBJ_GFX_RIVAL_MAY_WATERING             0x5F

#define EVENT_OBJ_GFX_LINK_BRENDAN                   0x60
#define EVENT_OBJ_GFX_LINK_RS_BRENDAN                0x61
#define EVENT_OBJ_GFX_RED                            0x62
#define EVENT_OBJ_GFX_DECORATING_PROTAG_BOY5         0x63
#define EVENT_OBJ_GFX_DECORATING_PROTAG_BOY1         0x64
#define EVENT_OBJ_GFX_DECORATING_PROTAG_BOY2         0x65
#define EVENT_OBJ_GFX_DECORATING_PROTAG_BOY3         0x66
#define EVENT_OBJ_GFX_DECORATING_PROTAG_BOY4         0x67
#define EVENT_OBJ_GFX_LINK_MAY                       0x68
#define EVENT_OBJ_GFX_LINK_RS_MAY                    0x69
#define EVENT_OBJ_GFX_LEAF                           0x6A
#define EVENT_OBJ_GFX_DECORATING_PROTAG_GIRL5        0x6B
#define EVENT_OBJ_GFX_DECORATING_PROTAG_GIRL1        0x6C
#define EVENT_OBJ_GFX_DECORATING_PROTAG_GIRL2        0x6D
#define EVENT_OBJ_GFX_DECORATING_PROTAG_GIRL3        0x6E
#define EVENT_OBJ_GFX_DECORATING_PROTAG_GIRL4        0x6F


#define EVENT_OBJ_GFX_NINJA_BOY                      0x70
#define EVENT_OBJ_GFX_TWIN                           0x71
#define EVENT_OBJ_GFX_BOY_1                          0x72
#define EVENT_OBJ_GFX_GIRL_1                         0x73
#define EVENT_OBJ_GFX_BOY_2                          0x74
#define EVENT_OBJ_GFX_GIRL_2                         0x75
#define EVENT_OBJ_GFX_LITTLE_BOY                     0x76
#define EVENT_OBJ_GFX_LITTLE_GIRL                    0x77
#define EVENT_OBJ_GFX_BOY_3                          0x78
#define EVENT_OBJ_GFX_GIRL_3                         0x79
#define EVENT_OBJ_GFX_RICH_BOY                       0x7A
#define EVENT_OBJ_GFX_WOMAN_1                        0x7B
#define EVENT_OBJ_GFX_FAT_MAN                        0x7C
#define EVENT_OBJ_GFX_POKEFAN_F                      0x7D
#define EVENT_OBJ_GFX_MAN_1                          0x7E
#define EVENT_OBJ_GFX_WOMAN_2                        0x7F
#define EVENT_OBJ_GFX_EXPERT_M                       0x80
#define EVENT_OBJ_GFX_EXPERT_F                       0x81
#define EVENT_OBJ_GFX_MAN_2                          0x82
#define EVENT_OBJ_GFX_WOMAN_3                        0x83
#define EVENT_OBJ_GFX_POKEFAN_M                      0x84
#define EVENT_OBJ_GFX_WOMAN_4                        0x85
#define EVENT_OBJ_GFX_COOK                           0x86
#define EVENT_OBJ_GFX_LINK_RECEPTIONIST              0x87
#define EVENT_OBJ_GFX_OLD_MAN                        0x88
#define EVENT_OBJ_GFX_OLD_WOMAN                      0x89
#define EVENT_OBJ_GFX_CAMPER                         0x8A
#define EVENT_OBJ_GFX_PICNICKER                      0x8B
#define EVENT_OBJ_GFX_MAN_3                          0x8C
#define EVENT_OBJ_GFX_WOMAN_5                        0x8D
#define EVENT_OBJ_GFX_POLICEMAN                      0x8E
#define EVENT_OBJ_GFX_YOUNGSTER                      0x8F
#define EVENT_OBJ_GFX_BUG_CATCHER                    0x90
#define EVENT_OBJ_GFX_PSYCHIC_M                      0x91
#define EVENT_OBJ_GFX_SCHOOL_KID_M                   0x92
#define EVENT_OBJ_GFX_MANIAC                         0x93
#define EVENT_OBJ_GFX_HEX_MANIAC                     0x94
#define EVENT_OBJ_GFX_RAYQUAZA_1                     0x95
#define EVENT_OBJ_GFX_SWIMMER_M                      0x96
#define EVENT_OBJ_GFX_SWIMMER_F                      0x97
#define EVENT_OBJ_GFX_BLACK_BELT                     0x98
#define EVENT_OBJ_GFX_BEAUTY                         0x99
#define EVENT_OBJ_GFX_SCIENTIST_1                    0x9A
#define EVENT_OBJ_GFX_LASS                           0x9B
#define EVENT_OBJ_GFX_GENTLEMAN                      0x9C
#define EVENT_OBJ_GFX_SAILOR                         0x9D
#define EVENT_OBJ_GFX_FISHERMAN                      0x9E
#define EVENT_OBJ_GFX_RUNNING_TRIATHLETE_M           0x9F
#define EVENT_OBJ_GFX_RUNNING_TRIATHLETE_F           0xA0
#define EVENT_OBJ_GFX_TUBER_F                        0xA1
#define EVENT_OBJ_GFX_TUBER_M                        0xA2
#define EVENT_OBJ_GFX_HIKER                          0xA3
#define EVENT_OBJ_GFX_CYCLING_TRIATHLETE_M           0xA4
#define EVENT_OBJ_GFX_CYCLING_TRIATHLETE_F           0xA5
#define EVENT_OBJ_GFX_NURSE                          0xA6
#define EVENT_OBJ_GFX_ITEM_BALL                      0xA7
#define EVENT_OBJ_GFX_TM_BALL                        0xA8
#define EVENT_OBJ_GFX_BERRY_TREE                     0xA9
#define EVENT_OBJ_GFX_BERRY_TREE_EARLY_STAGES        0xAA
#define EVENT_OBJ_GFX_BERRY_TREE_LATE_STAGES         0xAB
#define EVENT_OBJ_GFX_PROF_BIRCH                     0xAC
#define EVENT_OBJ_GFX_MAN_4                          0xAD
#define EVENT_OBJ_GFX_MAN_5                          0xAE
#define EVENT_OBJ_GFX_REPORTER_M                     0xAF
#define EVENT_OBJ_GFX_REPORTER_F                     0xB0
#define EVENT_OBJ_GFX_BARD                           0xB1
#define EVENT_OBJ_GFX_ANABEL                         0xB2
#define EVENT_OBJ_GFX_TUCKER                         0xB3
#define EVENT_OBJ_GFX_GRETA                          0xB4
#define EVENT_OBJ_GFX_SPENSER                        0xB5
#define EVENT_OBJ_GFX_NOLAND                         0xB6
#define EVENT_OBJ_GFX_LUCY                           0xB7
#define EVENT_OBJ_GFX_UNUSED_NATU_DOLL               0xB8
#define EVENT_OBJ_GFX_UNUSED_MAGNEMITE_DOLL          0xB9
#define EVENT_OBJ_GFX_UNUSED_SQUIRTLE_DOLL           0xBA
#define EVENT_OBJ_GFX_UNUSED_WOOPER_DOLL             0xBB
#define EVENT_OBJ_GFX_UNUSED_PIKACHU_DOLL            0xBC
#define EVENT_OBJ_GFX_UNUSED_PORYGON2_DOLL           0xBD
#define EVENT_OBJ_GFX_CUTTABLE_TREE                  0xBE
#define EVENT_OBJ_GFX_MART_EMPLOYEE                  0xBF
#define EVENT_OBJ_GFX_ROOFTOP_SALE_WOMAN             0xC0
#define EVENT_OBJ_GFX_TEALA                          0xC1
#define EVENT_OBJ_GFX_BREAKABLE_ROCK                 0xC2
#define EVENT_OBJ_GFX_PUSHABLE_BOULDER               0xC3
#define EVENT_OBJ_GFX_MR_BRINEYS_BOAT                0xC4
#define EVENT_OBJ_GFX_TRUCK                          0xC5
#define EVENT_OBJ_GFX_VIGOROTH_CARRYING_BOX          0xC6
#define EVENT_OBJ_GFX_VIGOROTH_FACING_AWAY           0xC7
#define EVENT_OBJ_GFX_BIRCHS_BAG                     0xC8
#define EVENT_OBJ_GFX_ZIGZAGOON_1                    0xC9
#define EVENT_OBJ_GFX_ARTIST                         0xCA
#define EVENT_OBJ_GFX_CAMERAMAN                      0xCB
#define EVENT_OBJ_GFX_MOVING_BOX                     0xCC
#define EVENT_OBJ_GFX_CABLE_CAR                      0xCD
#define EVENT_OBJ_GFX_SCIENTIST_2                    0xCE
#define EVENT_OBJ_GFX_DEVON_EMPLOYEE                 0xCF
#define EVENT_OBJ_GFX_AQUA_MEMBER_M                  0xD0
#define EVENT_OBJ_GFX_AQUA_MEMBER_F                  0xD1
#define EVENT_OBJ_GFX_MAGMA_MEMBER_M                 0xD2
#define EVENT_OBJ_GFX_MAGMA_MEMBER_F                 0xD3
#define EVENT_OBJ_GFX_SIDNEY                         0xD4
#define EVENT_OBJ_GFX_PHOEBE                         0xD5
#define EVENT_OBJ_GFX_GLACIA                         0xD6
#define EVENT_OBJ_GFX_DRAKE                          0xD7
#define EVENT_OBJ_GFX_ROXANNE                        0xD8
#define EVENT_OBJ_GFX_BRAWLY                         0xD9
#define EVENT_OBJ_GFX_WATTSON                        0xDA
#define EVENT_OBJ_GFX_FLANNERY                       0xDB
#define EVENT_OBJ_GFX_NORMAN                         0xDC
#define EVENT_OBJ_GFX_WINONA                         0xDD
#define EVENT_OBJ_GFX_LIZA                           0xDE
#define EVENT_OBJ_GFX_TATE                           0xDF
#define EVENT_OBJ_GFX_WALLACE                        0xE0
#define EVENT_OBJ_GFX_STEVEN                         0xE1
#define EVENT_OBJ_GFX_WALLY                          0xE2
#define EVENT_OBJ_GFX_LITTLE_BOY_3                   0xE3
#define EVENT_OBJ_GFX_HOT_SPRINGS_OLD_WOMAN          0xE4
#define EVENT_OBJ_GFX_SS_TIDAL                       0xE5
#define EVENT_OBJ_GFX_SUBMARINE_SHADOW               0xE6
#define EVENT_OBJ_GFX_PICHU_DOLL                     0xE7
#define EVENT_OBJ_GFX_PIKACHU_DOLL                   0xE8
#define EVENT_OBJ_GFX_MARILL_DOLL                    0xE9
#define EVENT_OBJ_GFX_TOGEPI_DOLL                    0xEA
#define EVENT_OBJ_GFX_CYNDAQUIL_DOLL                 0xEB
#define EVENT_OBJ_GFX_CHIKORITA_DOLL                 0xEC
#define EVENT_OBJ_GFX_TOTODILE_DOLL                  0xED
#define EVENT_OBJ_GFX_JIGGLYPUFF_DOLL                0xEE
#define EVENT_OBJ_GFX_MEOWTH_DOLL                    0xEF
#define EVENT_OBJ_GFX_CLEFAIRY_DOLL                  0xF0
#define EVENT_OBJ_GFX_DITTO_DOLL                     0xF1
#define EVENT_OBJ_GFX_SMOOCHUM_DOLL                  0xF2
#define EVENT_OBJ_GFX_TREECKO_DOLL                   0xF3
#define EVENT_OBJ_GFX_TORCHIC_DOLL                   0xF4
#define EVENT_OBJ_GFX_MUDKIP_DOLL                    0xF5
#define EVENT_OBJ_GFX_DUSKULL_DOLL                   0xF6
#define EVENT_OBJ_GFX_WYNAUT_DOLL                    0xF7
#define EVENT_OBJ_GFX_BALTOY_DOLL                    0xF8
#define EVENT_OBJ_GFX_KECLEON_DOLL                   0xF9
#define EVENT_OBJ_GFX_AZURILL_DOLL                   0xFA
#define EVENT_OBJ_GFX_SKITTY_DOLL                    0xFB
#define EVENT_OBJ_GFX_SWABLU_DOLL                    0xFC
#define EVENT_OBJ_GFX_GULPIN_DOLL                    0xFD
#define EVENT_OBJ_GFX_LOTAD_DOLL                     0xFE
#define EVENT_OBJ_GFX_SEEDOT_DOLL                    0xFF
#define EVENT_OBJ_GFX_PIKA_CUSHION                  0x100
#define EVENT_OBJ_GFX_ROUND_CUSHION                 0x101
#define EVENT_OBJ_GFX_KISS_CUSHION                  0x102
#define EVENT_OBJ_GFX_ZIGZAG_CUSHION                0x103
#define EVENT_OBJ_GFX_SPIN_CUSHION                  0x104
#define EVENT_OBJ_GFX_DIAMOND_CUSHION               0x105
#define EVENT_OBJ_GFX_BALL_CUSHION                  0x106
#define EVENT_OBJ_GFX_GRASS_CUSHION                 0x107
#define EVENT_OBJ_GFX_FIRE_CUSHION                  0x108
#define EVENT_OBJ_GFX_WATER_CUSHION                 0x109
#define EVENT_OBJ_GFX_BIG_SNORLAX_DOLL              0x10A
#define EVENT_OBJ_GFX_BIG_RHYDON_DOLL               0x10B
#define EVENT_OBJ_GFX_BIG_LAPRAS_DOLL               0x10C
#define EVENT_OBJ_GFX_BIG_VENUSAUR_DOLL             0x10D
#define EVENT_OBJ_GFX_BIG_CHARIZARD_DOLL            0x10E
#define EVENT_OBJ_GFX_BIG_BLASTOISE_DOLL            0x10F
#define EVENT_OBJ_GFX_BIG_WAILMER_DOLL              0x110
#define EVENT_OBJ_GFX_BIG_REGIROCK_DOLL             0x111
#define EVENT_OBJ_GFX_BIG_REGICE_DOLL               0x112
#define EVENT_OBJ_GFX_BIG_REGISTEEL_DOLL            0x113
#define EVENT_OBJ_GFX_LATIAS                        0x114
#define EVENT_OBJ_GFX_LATIOS                        0x115
#define EVENT_OBJ_GFX_GAMEBOY_KID                   0x116
#define EVENT_OBJ_GFX_CONTEST_JUDGE                 0x117
#define EVENT_OBJ_GFX_ARCHIE                        0x118
#define EVENT_OBJ_GFX_MAXIE                         0x119
#define EVENT_OBJ_GFX_KYOGRE_1                      0x11A
#define EVENT_OBJ_GFX_GROUDON_1                     0x11B
#define EVENT_OBJ_GFX_FOSSIL                        0x11C
#define EVENT_OBJ_GFX_REGIROCK                      0x11D
#define EVENT_OBJ_GFX_REGICE                        0x11E
#define EVENT_OBJ_GFX_REGISTEEL                     0x11F
#define EVENT_OBJ_GFX_SKITTY                        0x120
#define EVENT_OBJ_GFX_KECLEON_1                     0x121
#define EVENT_OBJ_GFX_KYOGRE_2                      0x122
#define EVENT_OBJ_GFX_GROUDON_2                     0x123
#define EVENT_OBJ_GFX_RAYQUAZA_2                    0x124
#define EVENT_OBJ_GFX_ZIGZAGOON_2                   0x125
#define EVENT_OBJ_GFX_PIKACHU                       0x126
#define EVENT_OBJ_GFX_AZUMARILL                     0x127
#define EVENT_OBJ_GFX_WINGULL                       0x128
#define EVENT_OBJ_GFX_KECLEON_2                     0x129
#define EVENT_OBJ_GFX_TUBER_M_SWIMMING              0x12A
#define EVENT_OBJ_GFX_AZURILL                       0x12B
#define EVENT_OBJ_GFX_MOM                           0x12C
#define EVENT_OBJ_GFX_DAD                           0x12D
#define EVENT_OBJ_GFX_JUAN                          0x12E
#define EVENT_OBJ_GFX_SCOTT                         0x12F
#define EVENT_OBJ_GFX_POOCHYENA                     0x130
#define EVENT_OBJ_GFX_KYOGRE_3                      0x131
#define EVENT_OBJ_GFX_GROUDON_3                     0x132
#define EVENT_OBJ_GFX_MYSTERY_GIFT_MAN              0x133
#define EVENT_OBJ_GFX_TRICK_HOUSE_STATUE            0x134
#define EVENT_OBJ_GFX_KIRLIA                        0x135
#define EVENT_OBJ_GFX_DUSCLOPS                      0x136
#define EVENT_OBJ_GFX_UNION_ROOM_NURSE              0x137
#define EVENT_OBJ_GFX_SUDOWOODO                     0x138
#define EVENT_OBJ_GFX_MEW                           0x139
#define EVENT_OBJ_GFX_DEOXYS                        0x13A
#define EVENT_OBJ_GFX_DEOXYS_TRIANGLE               0x13B
#define EVENT_OBJ_GFX_BRANDON                       0x13C
#define EVENT_OBJ_GFX_LUGIA                         0x13D
#define EVENT_OBJ_GFX_HOOH                          0x13E
#define EVENT_OBJ_GFX_LETTER                        0x13F
#define EVENT_OBJ_GFX_CHAIR_ITEMS_1                 0x140
#define EVENT_OBJ_GFX_CHAIR_ITEMS_2                 0x141
#define EVENT_OBJ_GFX_CHAIR_ITEMS_3                 0x142
#define EVENT_OBJ_GFX_CHAIR_ITEMS_4                 0x143
#define EVENT_OBJ_GFX_CHAIR_ITEMS_5                 0x144
#define EVENT_OBJ_GFX_FORMER_AQUA_M                 0x145
#define EVENT_OBJ_GFX_FORMER_AQUA_F                 0x146
#define EVENT_OBJ_GFX_FORMER_MAGMA_M                0x147
#define EVENT_OBJ_GFX_AQUA_FRIEND_M                 0x148
#define EVENT_OBJ_GFX_AQUA_FRIEND_F                 0x149
#define EVENT_OBJ_GFX_FORMER_AQUA_FRIEND_M          0x14A
#define EVENT_OBJ_GFX_FORMER_AQUA_FRIEND_F          0x14B

#define EVENT_OBJ_GFX_BARD_2                        0x14C
#define NUM_OBJECT_GRAPHICS_INFO     EVENT_OBJ_GFX_BARD_2

// These are dynamic object gfx ids.
// They correspond with the values of the VAR_OBJ_GFX_ID_X vars.
// More info about them in include/constants/vars.h
#define EVENT_OBJ_GFX_VAR_0 0x1F0
#define EVENT_OBJ_GFX_VAR_1 0x1F1
#define EVENT_OBJ_GFX_VAR_2 0x1F2
#define EVENT_OBJ_GFX_VAR_3 0x1F3
#define EVENT_OBJ_GFX_VAR_4 0x1F4
#define EVENT_OBJ_GFX_VAR_5 0x1F5
#define EVENT_OBJ_GFX_VAR_6 0x1F6
#define EVENT_OBJ_GFX_VAR_7 0x1F7
#define EVENT_OBJ_GFX_VAR_8 0x1F8
#define EVENT_OBJ_GFX_VAR_9 0x1F9
#define EVENT_OBJ_GFX_VAR_A 0x1FA
#define EVENT_OBJ_GFX_VAR_B 0x1FB
#define EVENT_OBJ_GFX_VAR_C 0x1FC
#define EVENT_OBJ_GFX_VAR_D 0x1FD
#define EVENT_OBJ_GFX_VAR_E 0x1FE
#define EVENT_OBJ_GFX_VAR_F 0x1FF

#define SPRITE_VAR EVENT_OBJ_GFX_VAR_0

#define SHADOW_SIZE_S   0
#define SHADOW_SIZE_M   1
#define SHADOW_SIZE_L   2
#define SHADOW_SIZE_XL  3

#define F_INANIMATE                        (1 << 6)
#define F_DISABLE_REFLECTION_PALETTE_LOAD  (1 << 7)

#define TRACKS_NONE       0
#define TRACKS_FOOT       1
#define TRACKS_BIKE_TIRE  2

#define FIRST_DECORATION_SPRITE_GFX EVENT_OBJ_GFX_PICHU_DOLL

#define EVENT_OBJ_ID_PLAYER 0xFF
#define EVENT_OBJ_ID_CAMERA 0x7F
#define LID_PLAYER 0xFF

#endif  // GUARD_CONSTANTS_EVENT_OBJECTS_H
