#ifndef GUARD_CONSTANTS_EVENT_OBJECTS_H
#define GUARD_CONSTANTS_EVENT_OBJECTS_H

#define EVENT_OBJ_GFX_BRENDAN_NORMAL               0
#define EVENT_OBJ_GFX_BRENDAN_MACH_BIKE            1
#define EVENT_OBJ_GFX_BRENDAN_SURFING              2
#define EVENT_OBJ_GFX_BRENDAN_FIELD_MOVE           3
#define EVENT_OBJ_GFX_QUINTY_PLUMP                 4
#define EVENT_OBJ_GFX_NINJA_BOY                    5
#define EVENT_OBJ_GFX_TWIN                         6
#define EVENT_OBJ_GFX_BOY_1                        7
#define EVENT_OBJ_GFX_GIRL_1                       8
#define EVENT_OBJ_GFX_BOY_2                        9
#define EVENT_OBJ_GFX_GIRL_2                      10
#define EVENT_OBJ_GFX_LITTLE_BOY                  11
#define EVENT_OBJ_GFX_LITTLE_GIRL                 12
#define EVENT_OBJ_GFX_BOY_3                       13
#define EVENT_OBJ_GFX_GIRL_3                      14
#define EVENT_OBJ_GFX_RICH_BOY                    15
#define EVENT_OBJ_GFX_WOMAN_1                     16
#define EVENT_OBJ_GFX_FAT_MAN                     17
#define EVENT_OBJ_GFX_POKEFAN_F                   18
#define EVENT_OBJ_GFX_MAN_1                       19
#define EVENT_OBJ_GFX_WOMAN_2                     20
#define EVENT_OBJ_GFX_EXPERT_M                    21
#define EVENT_OBJ_GFX_EXPERT_F                    22
#define EVENT_OBJ_GFX_MAN_2                       23
#define EVENT_OBJ_GFX_WOMAN_3                     24
#define EVENT_OBJ_GFX_POKEFAN_M                   25
#define EVENT_OBJ_GFX_WOMAN_4                     26
#define EVENT_OBJ_GFX_COOK                        27
#define EVENT_OBJ_GFX_LINK_RECEPTIONIST           28
#define EVENT_OBJ_GFX_OLD_MAN                     29
#define EVENT_OBJ_GFX_OLD_WOMAN                   30
#define EVENT_OBJ_GFX_CAMPER                      31
#define EVENT_OBJ_GFX_PICNICKER                   32
#define EVENT_OBJ_GFX_MAN_3                       33
#define EVENT_OBJ_GFX_WOMAN_5                     34
#define EVENT_OBJ_GFX_POLICEMAN                   35
#define EVENT_OBJ_GFX_YOUNGSTER                   36
#define EVENT_OBJ_GFX_BUG_CATCHER                 37
#define EVENT_OBJ_GFX_PSYCHIC_M                   38
#define EVENT_OBJ_GFX_SCHOOL_KID_M                39
#define EVENT_OBJ_GFX_MANIAC                      40
#define EVENT_OBJ_GFX_HEX_MANIAC                  41
#define EVENT_OBJ_GFX_RAYQUAZA_1                  42
#define EVENT_OBJ_GFX_SWIMMER_M                   43
#define EVENT_OBJ_GFX_SWIMMER_F                   44
#define EVENT_OBJ_GFX_BLACK_BELT                  45
#define EVENT_OBJ_GFX_BEAUTY                      46
#define EVENT_OBJ_GFX_SCIENTIST_1                 47
#define EVENT_OBJ_GFX_LASS                        48
#define EVENT_OBJ_GFX_GENTLEMAN                   49
#define EVENT_OBJ_GFX_SAILOR                      50
#define EVENT_OBJ_GFX_FISHERMAN                   51
#define EVENT_OBJ_GFX_RUNNING_TRIATHLETE_M        52
#define EVENT_OBJ_GFX_RUNNING_TRIATHLETE_F        53
#define EVENT_OBJ_GFX_TUBER_F                     54
#define EVENT_OBJ_GFX_TUBER_M                     55
#define EVENT_OBJ_GFX_HIKER                       56
#define EVENT_OBJ_GFX_CYCLING_TRIATHLETE_M        57
#define EVENT_OBJ_GFX_CYCLING_TRIATHLETE_F        58
#define EVENT_OBJ_GFX_NURSE                       59
#define EVENT_OBJ_GFX_ITEM_BALL                   60
#define EVENT_OBJ_GFX_BERRY_TREE                  61
#define EVENT_OBJ_GFX_BERRY_TREE_EARLY_STAGES     62
#define EVENT_OBJ_GFX_BERRY_TREE_LATE_STAGES      63
#define EVENT_OBJ_GFX_BRENDAN_ACRO_BIKE           64
#define EVENT_OBJ_GFX_PROF_BIRCH                  65
#define EVENT_OBJ_GFX_MAN_4                       66
#define EVENT_OBJ_GFX_MAN_5                       67
#define EVENT_OBJ_GFX_REPORTER_M                  68
#define EVENT_OBJ_GFX_REPORTER_F                  69
#define EVENT_OBJ_GFX_BARD                        70
#define EVENT_OBJ_GFX_ANABEL                      71
#define EVENT_OBJ_GFX_TUCKER                      72
#define EVENT_OBJ_GFX_GRETA                       73
#define EVENT_OBJ_GFX_SPENSER                     74
#define EVENT_OBJ_GFX_NOLAND                      75
#define EVENT_OBJ_GFX_LUCY                        76
#define EVENT_OBJ_GFX_UNUSED_NATU_DOLL            77
#define EVENT_OBJ_GFX_UNUSED_MAGNEMITE_DOLL       78
#define EVENT_OBJ_GFX_UNUSED_SQUIRTLE_DOLL        79
#define EVENT_OBJ_GFX_UNUSED_WOOPER_DOLL          80
#define EVENT_OBJ_GFX_UNUSED_PIKACHU_DOLL         81
#define EVENT_OBJ_GFX_UNUSED_PORYGON2_DOLL        82
#define EVENT_OBJ_GFX_CUTTABLE_TREE               83
#define EVENT_OBJ_GFX_MART_EMPLOYEE               84
#define EVENT_OBJ_GFX_ROOFTOP_SALE_WOMAN          85
#define EVENT_OBJ_GFX_TEALA                       86
#define EVENT_OBJ_GFX_BREAKABLE_ROCK              87
#define EVENT_OBJ_GFX_PUSHABLE_BOULDER            88
#define EVENT_OBJ_GFX_MR_BRINEYS_BOAT             89
#define EVENT_OBJ_GFX_MAY_NORMAL                  90
#define EVENT_OBJ_GFX_MAY_MACH_BIKE               91
#define EVENT_OBJ_GFX_MAY_ACRO_BIKE               92
#define EVENT_OBJ_GFX_MAY_SURFING                 93
#define EVENT_OBJ_GFX_MAY_FIELD_MOVE              94
#define EVENT_OBJ_GFX_TRUCK                       95
#define EVENT_OBJ_GFX_VIGOROTH_CARRYING_BOX       96
#define EVENT_OBJ_GFX_VIGOROTH_FACING_AWAY        97
#define EVENT_OBJ_GFX_BIRCHS_BAG                  98
#define EVENT_OBJ_GFX_ZIGZAGOON_1                 99
#define EVENT_OBJ_GFX_ARTIST                      100
#define EVENT_OBJ_GFX_RIVAL_BRENDAN_NORMAL       101
#define EVENT_OBJ_GFX_RIVAL_BRENDAN_MACH_BIKE    102
#define EVENT_OBJ_GFX_RIVAL_BRENDAN_ACRO_BIKE    103
#define EVENT_OBJ_GFX_RIVAL_BRENDAN_SURFING      104
#define EVENT_OBJ_GFX_RIVAL_BRENDAN_FIELD_MOVE   105
#define EVENT_OBJ_GFX_RIVAL_MAY_NORMAL           106
#define EVENT_OBJ_GFX_RIVAL_MAY_MACH_BIKE        107
#define EVENT_OBJ_GFX_RIVAL_MAY_ACRO_BIKE        108
#define EVENT_OBJ_GFX_RIVAL_MAY_SURFING          109
#define EVENT_OBJ_GFX_RIVAL_MAY_FIELD_MOVE       110
#define EVENT_OBJ_GFX_CAMERAMAN                  111
#define EVENT_OBJ_GFX_BRENDAN_UNDERWATER         112
#define EVENT_OBJ_GFX_MAY_UNDERWATER             113
#define EVENT_OBJ_GFX_MOVING_BOX                 114
#define EVENT_OBJ_GFX_CABLE_CAR                  115
#define EVENT_OBJ_GFX_SCIENTIST_2                116
#define EVENT_OBJ_GFX_DEVON_EMPLOYEE             117
#define EVENT_OBJ_GFX_AQUA_MEMBER_M              118
#define EVENT_OBJ_GFX_AQUA_MEMBER_F              119
#define EVENT_OBJ_GFX_MAGMA_MEMBER_M             120
#define EVENT_OBJ_GFX_MAGMA_MEMBER_F             121
#define EVENT_OBJ_GFX_SIDNEY                     122
#define EVENT_OBJ_GFX_PHOEBE                     123
#define EVENT_OBJ_GFX_GLACIA                     124
#define EVENT_OBJ_GFX_DRAKE                      125
#define EVENT_OBJ_GFX_ROXANNE                    126
#define EVENT_OBJ_GFX_BRAWLY                     127
#define EVENT_OBJ_GFX_WATTSON                    128
#define EVENT_OBJ_GFX_FLANNERY                   129
#define EVENT_OBJ_GFX_NORMAN                     130
#define EVENT_OBJ_GFX_WINONA                     131
#define EVENT_OBJ_GFX_LIZA                       132
#define EVENT_OBJ_GFX_TATE                       133
#define EVENT_OBJ_GFX_WALLACE                    134
#define EVENT_OBJ_GFX_STEVEN                     135
#define EVENT_OBJ_GFX_WALLY                      136
#define EVENT_OBJ_GFX_LITTLE_BOY_3               137
#define EVENT_OBJ_GFX_BRENDAN_FISHING            138
#define EVENT_OBJ_GFX_MAY_FISHING                139
#define EVENT_OBJ_GFX_HOT_SPRINGS_OLD_WOMAN      140
#define EVENT_OBJ_GFX_SS_TIDAL                   141
#define EVENT_OBJ_GFX_SUBMARINE_SHADOW           142
#define EVENT_OBJ_GFX_PICHU_DOLL                 143
#define EVENT_OBJ_GFX_PIKACHU_DOLL               144
#define EVENT_OBJ_GFX_MARILL_DOLL                145
#define EVENT_OBJ_GFX_TOGEPI_DOLL                146
#define EVENT_OBJ_GFX_CYNDAQUIL_DOLL             147
#define EVENT_OBJ_GFX_CHIKORITA_DOLL             148
#define EVENT_OBJ_GFX_TOTODILE_DOLL              149
#define EVENT_OBJ_GFX_JIGGLYPUFF_DOLL            150
#define EVENT_OBJ_GFX_MEOWTH_DOLL                151
#define EVENT_OBJ_GFX_CLEFAIRY_DOLL              152
#define EVENT_OBJ_GFX_DITTO_DOLL                 153
#define EVENT_OBJ_GFX_SMOOCHUM_DOLL              154
#define EVENT_OBJ_GFX_TREECKO_DOLL               155
#define EVENT_OBJ_GFX_TORCHIC_DOLL               156
#define EVENT_OBJ_GFX_MUDKIP_DOLL                157
#define EVENT_OBJ_GFX_DUSKULL_DOLL               158
#define EVENT_OBJ_GFX_WYNAUT_DOLL                159
#define EVENT_OBJ_GFX_BALTOY_DOLL                160
#define EVENT_OBJ_GFX_KECLEON_DOLL               161
#define EVENT_OBJ_GFX_AZURILL_DOLL               162
#define EVENT_OBJ_GFX_SKITTY_DOLL                163
#define EVENT_OBJ_GFX_SWABLU_DOLL                164
#define EVENT_OBJ_GFX_GULPIN_DOLL                165
#define EVENT_OBJ_GFX_LOTAD_DOLL                 166
#define EVENT_OBJ_GFX_SEEDOT_DOLL                167
#define EVENT_OBJ_GFX_PIKA_CUSHION               168
#define EVENT_OBJ_GFX_ROUND_CUSHION              169
#define EVENT_OBJ_GFX_KISS_CUSHION               170
#define EVENT_OBJ_GFX_ZIGZAG_CUSHION             171
#define EVENT_OBJ_GFX_SPIN_CUSHION               172
#define EVENT_OBJ_GFX_DIAMOND_CUSHION            173
#define EVENT_OBJ_GFX_BALL_CUSHION               174
#define EVENT_OBJ_GFX_GRASS_CUSHION              175
#define EVENT_OBJ_GFX_FIRE_CUSHION               176
#define EVENT_OBJ_GFX_WATER_CUSHION              177
#define EVENT_OBJ_GFX_BIG_SNORLAX_DOLL           178
#define EVENT_OBJ_GFX_BIG_RHYDON_DOLL            179
#define EVENT_OBJ_GFX_BIG_LAPRAS_DOLL            180
#define EVENT_OBJ_GFX_BIG_VENUSAUR_DOLL          181
#define EVENT_OBJ_GFX_BIG_CHARIZARD_DOLL         182
#define EVENT_OBJ_GFX_BIG_BLASTOISE_DOLL         183
#define EVENT_OBJ_GFX_BIG_WAILMER_DOLL           184
#define EVENT_OBJ_GFX_BIG_REGIROCK_DOLL          185
#define EVENT_OBJ_GFX_BIG_REGICE_DOLL            186
#define EVENT_OBJ_GFX_BIG_REGISTEEL_DOLL         187
#define EVENT_OBJ_GFX_LATIAS                     188
#define EVENT_OBJ_GFX_LATIOS                     189
#define EVENT_OBJ_GFX_GAMEBOY_KID                190
#define EVENT_OBJ_GFX_CONTEST_JUDGE              191
#define EVENT_OBJ_GFX_BRENDAN_WATERING           192
#define EVENT_OBJ_GFX_MAY_WATERING               193
#define EVENT_OBJ_GFX_BRENDAN_DECORATING         194
#define EVENT_OBJ_GFX_MAY_DECORATING             195
#define EVENT_OBJ_GFX_ARCHIE                     196
#define EVENT_OBJ_GFX_MAXIE                      197
#define EVENT_OBJ_GFX_KYOGRE_1                   198
#define EVENT_OBJ_GFX_GROUDON_1                  199
#define EVENT_OBJ_GFX_FOSSIL                     200
#define EVENT_OBJ_GFX_REGIROCK                   201
#define EVENT_OBJ_GFX_REGICE                     202
#define EVENT_OBJ_GFX_REGISTEEL                  203
#define EVENT_OBJ_GFX_SKITTY                     204
#define EVENT_OBJ_GFX_KECLEON_1                  205
#define EVENT_OBJ_GFX_KYOGRE_2                   206
#define EVENT_OBJ_GFX_GROUDON_2                  207
#define EVENT_OBJ_GFX_RAYQUAZA_2                 208
#define EVENT_OBJ_GFX_ZIGZAGOON_2                209
#define EVENT_OBJ_GFX_PIKACHU                    210
#define EVENT_OBJ_GFX_AZUMARILL                  211
#define EVENT_OBJ_GFX_WINGULL                    212
#define EVENT_OBJ_GFX_KECLEON_2                  213
#define EVENT_OBJ_GFX_TUBER_M_SWIMMING           214
#define EVENT_OBJ_GFX_AZURILL                    215
#define EVENT_OBJ_GFX_MOM                        216
#define EVENT_OBJ_GFX_LINK_BRENDAN               217
#define EVENT_OBJ_GFX_LINK_MAY                   218
#define EVENT_OBJ_GFX_JUAN                       219
#define EVENT_OBJ_GFX_SCOTT                      220
#define EVENT_OBJ_GFX_POOCHYENA                  221
#define EVENT_OBJ_GFX_KYOGRE_3                   222
#define EVENT_OBJ_GFX_GROUDON_3                  223
#define EVENT_OBJ_GFX_MYSTERY_GIFT_MAN           224
#define EVENT_OBJ_GFX_TRICK_HOUSE_STATUE         225
#define EVENT_OBJ_GFX_KIRLIA                     226
#define EVENT_OBJ_GFX_DUSCLOPS                   227
#define EVENT_OBJ_GFX_UNION_ROOM_NURSE           228
#define EVENT_OBJ_GFX_SUDOWOODO                  229
#define EVENT_OBJ_GFX_MEW                        230
#define EVENT_OBJ_GFX_RED                        231
#define EVENT_OBJ_GFX_LEAF                       232
#define EVENT_OBJ_GFX_DEOXYS                     233
#define EVENT_OBJ_GFX_DEOXYS_TRIANGLE            234
#define EVENT_OBJ_GFX_BRANDON                    235
#define EVENT_OBJ_GFX_LINK_RS_BRENDAN            236
#define EVENT_OBJ_GFX_LINK_RS_MAY                237
#define EVENT_OBJ_GFX_LUGIA                      238
#define EVENT_OBJ_GFX_HOOH                       239
#define EVENT_OBJ_GFX_BARD_2                     240

// These are dynamic object gfx ids.
// They correspond with the values of the VAR_OBJ_GFX_ID_X vars.
// More info about them in include/constants/vars.h
#define EVENT_OBJ_GFX_VAR_0 241
#define EVENT_OBJ_GFX_VAR_1 242
#define EVENT_OBJ_GFX_VAR_2 243
#define EVENT_OBJ_GFX_VAR_3 244
#define EVENT_OBJ_GFX_VAR_4 245
#define EVENT_OBJ_GFX_VAR_5 246
#define EVENT_OBJ_GFX_VAR_6 247
#define EVENT_OBJ_GFX_VAR_7 248
#define EVENT_OBJ_GFX_VAR_8 249
#define EVENT_OBJ_GFX_VAR_9 250
#define EVENT_OBJ_GFX_VAR_A 251
#define EVENT_OBJ_GFX_VAR_B 252
#define EVENT_OBJ_GFX_VAR_C 253
#define EVENT_OBJ_GFX_VAR_D 254
#define EVENT_OBJ_GFX_VAR_E 255
#define EVENT_OBJ_GFX_VAR_F 256

#define SHADOW_SIZE_S   0
#define SHADOW_SIZE_M   1
#define SHADOW_SIZE_L   2
#define SHADOW_SIZE_XL  3

#define F_INANIMATE                        (1 << 6)
#define F_DISABLE_REFLECTION_PALETTE_LOAD  (1 << 7)

#define TRACKS_NONE       0
#define TRACKS_FOOT       1
#define TRACKS_BIKE_TIRE  2

#define FIRST_DECORATION_SPRITE_GFX EVENT_OBJ_GFX_PICHU_DOLL

#define EVENT_OBJ_ID_PLAYER 0xFF
#define EVENT_OBJ_ID_CAMERA 0x7F

#endif  // GUARD_CONSTANTS_EVENT_OBJECTS_H
