PetalburgCity_Gym_Text_2A6D3D: @ 82A6D3D
	.string "Norman: Hi, {PLAYER}!\p"
	.string "I just received a very rare BERRY.\n"
	.string "I'd like you to have it.$"



Route111_Text_2A6EBD: @ 82A6EBD
	.string "I watered the plants every day.\n"
	.string "They grew lots of flowers.\p"
	.string "And they gave me lots of BERRIES, too.\p"
	.string "Here you go!\n"
	.string "You can have it!$"

Route111_Text_2A6F3D: @ 82A6F3D
	.string "I'm going to try really hard and make\n"
	.string "BERRIES in different colors.\p"
	.string "I hope you try hard, too!$"

Route111_Text_2A6F9A: @ 82A6F9A
	.string "I wonder what color BERRIES I'll look\n"
	.string "for today?$"

Route114_Text_2A6FCB: @ 82A6FCB
	.string "I love using the BERRY CRUSH machine,\n"
	.string "so I'm collecting BERRIES.\p"
	.string "I'll share one with you, if you'd like.$"

Route114_Text_2A7034: @ 82A7034
	.string "You should try the BERRY CRUSH\n"
	.string "machine with your friends.$"

Route114_Text_2A706E: @ 82A706E
	.string "Which BERRY should be planted?\n"
	.string "Should you use or hoard BERRIES?\p"
	.string "It's fun to think about.$"


Route123_BerryMastersHouse_Text_2A7386: @ 82A7386
	.string "You may call me the BERRY MASTER.\p"
	.string "I dream of filling the world with\n"
	.string "beautiful flowers, so I raise BERRIES\l"
	.string "and hand them out to everyone.\p"
	.string "You're deserving of one!$"

Route123_BerryMastersHouse_Text_2A7428: @ 82A7428
	.string "Why be stingy?\n"
	.string "Take another!$"

Route123_BerryMastersHouse_Text_2A7445: @ 82A7445
	.string "Be sure to visit the PRETTY PETAL\n"
	.string "flower shop near RUSTBORO.\p"
	.string "Let flowers fill the world!$"

Route123_BerryMastersHouse_Text_2A749E: @ 82A749E
	.string "I'm done for today.\n"
	.string "Come again another day.\p"
	.string "Let flowers fill the world!$"

Route123_BerryMastersHouse_Text_2A74E6: @ 82A74E6
	.string "The way my husband grows BERRIES,\n"
	.string "oh, he's the best in the world.\p"
	.string "He makes me proud, that he does.\p"
	.string "Incidentally, child, have you heard\n"
	.string "a good saying lately?$"

Route123_BerryMastersHouse_Text_2A7583: @ 82A7583
	.string "Ah! What a remarkable saying!\n"
	.string "Inspirational, it is!\p"
	.string "I want you to have this.$"

Route123_BerryMastersHouse_Text_2A75D0: @ 82A75D0
	.string "Oh! A good saying it is.\n"
	.string "You're quite remarkable.\p"
	.string "I want you to have this.$"

Route123_BerryMastersHouse_Text_2A761B: @ 82A761B
	.string "Our four grandchildren should become\n"
	.string "more accomplished than my husband.\p"
	.string "Joy never goes out of my life!$"

Route123_BerryMastersHouse_Text_2A7682: @ 82A7682
	.string "Ah…$"

