gText_Birch_Welcome:: @ 82C897B
	.string "Hello! Sorry to keep you waiting!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "My name is Birch.\p"
	.string "But everyone calls me the Pokémon\n"
	.string "Professor.\p" 
	.string "$"
	@ ^ The \p right before the end of the string provides
	@ in-built continue arrow and "waitmessage" functionality.

gText_Birch_Pokemon:: @ 82C89FB
	.string "This is what we call a “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "This world is widely inhabited by\n"
	.string "creatures known as Pokémon.\p"
	.string "They are dangerous creatures, more\n"
	.string "than capable of causing destruction\l"
	.string "and harm, all on their own.\p"
	.string "But in the right, caring hands, they\n"
	.string "can help maintain peace and provide\l"
	.string "resources we wouldn't have otherwise.\p"
	.string "Many people train Pokémon to battle.\p"
	.string "Many use Pokémon as workmates.\p"
	.string "Many are close friends and playmates\n"
	.string "with their Pokémon.\p"
	.string "I research them. There are still so\n"
	.string "many mysteries surrounding Pokémon.\l"
	.string "To unravel them all is my life's work.\p"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "What about you?$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_ControlBoy::
	.string "Boy {DPAD_LEFT}$"
gText_Birch_ControlGirl::
	.string "{DPAD_RIGHT} Girl$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "Striking!\n"
	.string "And what's your name?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it's {PLAYER}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Ah, yes!\p"
	.string "You're the {PLAYER_boy} who's moving to my\n"
	.string "hometown of Littleroot from Alola.\l"
	.string "I hear it's lovely there!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "All right, are you ready, {PLAYER}?\p"
	.string "Oh, what's with that look?\p"
	.string "Take courage, and leap into the\n"
	.string "world with head held high!\l"
	.string "I know you can do it if you try!\p"
	.string "Come see me in my lab later, and\n"
	.string "we can get you started off right!\p"
	.string "$"
