MossdeepCity_PokemonCenter_2F_MapScripts:: @ 8222334
	map_script MAP_SCRIPT_ON_TRANSITION, PokemonCenter_2F_OnTransition
	.byte 0

MossdeepCity_PokemonCenter_2F_EventScript_22235B:: @ 822235B
	msgbox MossdeepCity_PokemonCenter_2F_Text_222364, MSGBOX_NPC
	end

MossdeepCity_PokemonCenter_2F_Text_222364: @ 8222364
	.string "If I win a whole lot of link battles\n"
	.string "and show everyone how good I am,\l"
	.string "I might get a fan following!$"

