MossdeepCity_GameCorner_1F_MapScripts:: @ 8224B27
	.byte 0

MossdeepCity_GameCorner_1F_EventScript_BingoLeaderboards1:
	msgbox 
MossdeepCity_GameCorner_1F_Text_BingoLeaderboards1:
	.string "Tuesday Night Bingo Leaderboards:\n"
	.string "1. Gary\l"
	.string "2. Vince\l"
	.string "3. Betty\l4.$"
	

MossdeepCity_GameCorner_1F_EventScript_OldMan:: @ 8224B5D
	msgbox MossdeepCity_GameCorner_1F_Text_224B66, MSGBOX_NPC
	end
MossdeepCity_GameCorner_1F_Text_224B66: @ 8224B66
	.string "When I was young, I traveled the world\n"
	.string "as a Pokémon Trainer.\p"
	.string "Now that I've become an old buzzard,\n"
	.string "my only amusement is watching young\l"
	.string "trainers battle in my basement.\p"
	.string "… … … … What?! That's not weird!\n"
	.string "What is it with young people these days?$"



MossdeepCity_GameCorner_1F_Text_224BFD: @ 8224BFD
	.string "The door appears to be locked.$"

MossdeepCity_GameCorner_1F_Text_224C1C: @ 8224C1C
	.string "A trainer named {STR_VAR_1} is\n"
	.string "visiting my home.\p"
	.string "Would you like to challenge\n"
	.string "{STR_VAR_1}?$"

MossdeepCity_GameCorner_1F_Text_224C64: @ 8224C64
	.string "You won't battle? I'm disappointed\n"
	.string "that I can't see you battle…$"

MossdeepCity_GameCorner_1F_Text_224CA4: @ 8224CA4
	.string "Oh, good, good!\p"
	.string "But my house isn't all that sturdy.\p"
	.string "Could I ask you to keep it down to\n"
	.string "a 3-on-3 match?$"

MossdeepCity_GameCorner_1F_Text_224D0B: @ 8224D0B
	.string "Before you two battle, you should\n"
	.string "save your progress.$"

MossdeepCity_GameCorner_1F_Text_224D41: @ 8224D41
	.string "I hope to see a good match!$"

MossdeepCity_GameCorner_1F_Text_224D5D: @ 8224D5D
	.string "So, it became a standoff.\p"
	.string "It was a brilliant match in which\n"
	.string "neither side conceded a step!$"

MossdeepCity_GameCorner_1F_Text_224DB7: @ 8224DB7
	.string "That was superlative!\p"
	.string "Why, it was like seeing myself in\n"
	.string "my youth again!$"

MossdeepCity_GameCorner_1F_Text_224DFF: @ 8224DFF
	.string "Ah, too bad for you!\p"
	.string "But it was a good match.\n"
	.string "I hope you can win next time.$"

